language: python

python:
  - "2.7"

addons:
    apt:
        packages:
        - libsqlite3-0
        - libspatialite3

env:
  - DJANGO="Django>=1.6,<1.7"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install --global-option=build_ext --global-option='-USQLITE_OMIT_LOAD_EXTENSION' pysqlite; fi
  - CFLAGS=-I/usr/include/gdal pip install GDAL==1.10
  - pip install -q $DJANGO

script:
  - python -Wall tests/manage.py test test_core --settings=settings
