language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
    apt:
        packages:
        - binutils
        - libproj-dev
        - gdal-bin
        - libgdal-dev
        - spatialite-bin
        - libsqlite3-0
        - libspatialite3

env:
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<1.12"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install --global-option=build_ext --global-option='-USQLITE_OMIT_LOAD_EXTENSION' pysqlite; fi
  - CFLAGS=-I/usr/include/gdal pip install GDAL==1.10
  - pip install -q $DJANGO
  - pip install django-leaflet
  - pip install coveralls

script:
  - python -Wall tests/manage.py test test_core --settings=settings
  - coverage run --omit='quicktest.py,setup.py' --source=. tests/manage.py test tests

after_success: coveralls

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.5"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"

allow_failures:
  - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
