dist: bionic
language: python

services: postgresql

addons:
  apt:
    packages:
    - postgresql-10-postgis-2.4

install:
  - pip install -q $DJANGO
  - pip install django-leaflet
  - pip install pytz
  - pip install coveralls

script:
  - pip install psycopg2
  - python -Wall tests/manage.py test test_core --settings=settings
  - coverage run --omit='quicktest.py,setup.py' --source=. tests/manage.py test tests

after_success:
  - coveralls

jobs:
  fast_finish: true
  include:
    - python: "3.5"
      env: DJANGO="Django==2.0.*"
    - python: "3.6"
      env: DJANGO="Django==2.0.*"
    - python: "3.7"
      env: DJANGO="Django==2.0.*"
    - python: "3.5"
      env: DJANGO="Django==2.1.*"
    - python: "3.6"
      env: DJANGO="Django==2.1.*"
    - python: "3.7"
      env: DJANGO="Django==2.1.*"
    - python: "3.5"
      env: DJANGO="Django==2.2.*"
    - python: "3.6"
      env: DJANGO="Django==2.2.*"
    - python: "3.7"
      env: DJANGO="Django==2.2.*"
    - python: "3.8"
      env: DJANGO="Django==2.2.*"
    - python: "3.6"
      env: DJANGO="Django==3.0.*"
    - python: "3.7"
      env: DJANGO="Django==3.0.*"
    - python: "3.8"
      env: DJANGO="Django==3.0.*"
    - python: "3.6"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.7"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.8"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'

allow_failures:
  - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

notifications:
  email:
    on_success: change
    on_failure: always
