# Generated by Django 3.2.9 on 2022-06-13 11:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geomodeldiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('key_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(max_length=6)),
                ('old_data', models.TextField()),
                ('new_data', models.TextField()),
                ('applied', models.BooleanField(db_index=True, default=False)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modeldiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('key_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(max_length=6)),
                ('old_data', models.TextField()),
                ('new_data', models.TextField()),
                ('applied', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
